language: node_js

node_js:
  - lts/*

cache:
  npm: false
  directories:
    - "~/.pnpm-store"

before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  - pnpm config set store-dir ~/.pnpm-store

install:
  - pnpm install

script: 
  - pnpm docs:build
  
deploy: 
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vitepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master