[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = "doc/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run doc-build"
